### ISSUE TITLE
Duplicate IF Statement

### ISSUE THREAD

**Issue by patmagee** [Sentieon/Sentieon-WDL#1]
https://github.com/Sentieon/Sentieon-WDL/blob/87648bbd5ec3f041be29d7fdcbbd75adad79e18d/ccdg_fastq2vcf.wdl#L282

It appears you are performing a duplicate check for read groups. I believe you are inteneding to make sure that the number of input Fastq files matches?

```
 if [[ ${dollar}{#first_fastq[@]} -ne ${dollar}{#second_fastq[@]} ]]; then 
```

**Comment by DonFreed** [comment]
Should be fixed now. Thanks!
